In [1]:
# importing important libraries
import pandas as pd
import os

In [2]:
# File containing the saved emoji data
PROJECT_ROOT = os.path.dirname(os.getcwd())
data_folder = os.path.join(PROJECT_ROOT, "data")
stickers_data = os.path.join(data_folder,"../data/flaticon_stickers.csv")

In [3]:
stickers = pd.read_csv(stickers_data)
stickers

,image,title,tags
0,https://cdn-icons-png.flaticon.com/512/8349/83...,Motivation,"miscellaneous, lettering, typography, quote, p..."
1,https://cdn-icons-png.flaticon.com/512/8351/83...,Calm,"miscellaneous, lettering, positivity, motivati..."
2,https://cdn-icons-png.flaticon.com/512/8351/83...,Trying,"miscellaneous, lettering, positivity, motivati..."
3,https://cdn-icons-png.flaticon.com/512/8356/83...,Family,"people, love, family, gay, homosexual, relatives"
4,https://cdn-icons-png.flaticon.com/512/8356/83...,Family,"people, love, family, relatives"
...,...,...,...
40902,https://cdn-icons-png.flaticon.com/512/4860/48...,Science Fiction,"miscellaneous, Science fiction, robot, robotic..."
40903,https://cdn-icons-png.flaticon.com/512/4952/49...,Luxury,"people, woman, commerce, person, shopping bag,..."
40904,https://cdn-icons-png.flaticon.com/512/5020/50...,Curious,"sticker, animal, people, character, emoji, emo..."
40905,https://cdn-icons-png.flaticon.com/256/5940/59...,NaN,NaN
40906,https://cdn-icons-png.flaticon.com/256/7173/71...,NaN,NaN

In [4]:
from hashlib import md5
stickers['filename'] = stickers['image'].apply(lambda x: md5(x.encode()).hexdigest() + os.path.splitext(x)[-1])
stickers

,image,title,tags,filename
0,https://cdn-icons-png.flaticon.com/512/8349/83...,Motivation,"miscellaneous, lettering, typography, quote, p...",91e5e79529778992008f0f77e4c080c4.png
1,https://cdn-icons-png.flaticon.com/512/8351/83...,Calm,"miscellaneous, lettering, positivity, motivati...",ac83e930f96b3192a9d03ebaf4618807.png
2,https://cdn-icons-png.flaticon.com/512/8351/83...,Trying,"miscellaneous, lettering, positivity, motivati...",2b7afb3382e915ecc5f90b32f316e776.png
3,https://cdn-icons-png.flaticon.com/512/8356/83...,Family,"people, love, family, gay, homosexual, relatives",2fbde21360a8ddf99949459a90004f33.png
4,https://cdn-icons-png.flaticon.com/512/8356/83...,Family,"people, love, family, relatives",617a3f0ef0d2ef5d246eb06b3ed5fbf4.png
...,...,...,...,...
40902,https://cdn-icons-png.flaticon.com/512/4860/48...,Science Fiction,"miscellaneous, Science fiction, robot, robotic...",c3e9e479c608c02df8727f7c55b2c8c7.png
40903,https://cdn-icons-png.flaticon.com/512/4952/49...,Luxury,"people, woman, commerce, person, shopping bag,...",da5f3a3f9071403b3a7c021293538dbb.png
40904,https://cdn-icons-png.flaticon.com/512/5020/50...,Curious,"sticker, animal, people, character, emoji, emo...",26e533ab0e81f90a327b890ed361dd61.png
40905,https://cdn-icons-png.flaticon.com/256/5940/59...,NaN,NaN,c6de95e1b7b2f3cfe5ae9a44986c5d03.png
40906,https://cdn-icons-png.flaticon.com/256/7173/71...,NaN,NaN,e7b5c06a2d41465ea3e2a5b7e18b20d8.png

In [5]:
stickers.to_csv()

',image,title,tags,filename\r\n0,https://cdn-icons-png.flaticon.com/512/8349/8349693.png,Motivation,"miscellaneous, lettering, typography, quote, positivity, motivation, motivational, motivate",91e5e79529778992008f0f77e4c080c4.png\r\n1,https://cdn-icons-png.flaticon.com/512/8351/8351056.png,Calm,"miscellaneous, lettering, positivity, motivation, motivational, motivate, positive, calm",ac83e930f96b3192a9d03ebaf4618807.png\r\n2,https://cdn-icons-png.flaticon.com/512/8351/8351126.png,Trying,"miscellaneous, lettering, positivity, motivation, motivational, motivate, positive",2b7afb3382e915ecc5f90b32f316e776.png\r\n3,https://cdn-icons-png.flaticon.com/512/8356/8356693.png,Family,"people, love, family, gay, homosexual, relatives",2fbde21360a8ddf99949459a90004f33.png\r\n4,https://cdn-icons-png.flaticon.com/512/8356/8356696.png,Family,"people, love, family, relatives",617a3f0ef0d2ef5d246eb06b3ed5fbf4.png\r\n5,https://cdn-icons-png.flaticon.com/256/8356/8356698.png,Access Denied,,d0ef7b0febe9e64707175d30338d6584.png\r\n6,https://cdn-icons-png.flaticon.com/512/8359/8359767.png,Holiday,"holidays, holiday, time and date, calendar, desk",478a953a9468c40b2ef99e81dd1b6c1b.png\r\n7,https://cdn-icons-png.flaticon.com/512/8359/8359788.png,Lipstick,"birthday and party, fashion, grooming, female, lipstick, feminine",ad92c2a592a552ecd70437795d3a0ac2.png\r\n8,https://cdn-icons-png.flaticon.com/512/8359/8359799.png,Mental Care,"miscellaneous, thinking, mental care",ebba19973ad7a1bd35a02e53a1f57694.png\r\n9,https://cdn-icons-png.flaticon.com/512/8359/8359956.png,Tape Recorder,"professions and jobs, music and multimedia, electronics, vintage, retro",d12308b31301697ae3095170d2a69b34.png\r\n10,https://cdn-icons-png.flaticon.com/256/8360/8360005.png,Access Denied,,a6438d3c3f2a20f914be80edc4444ab7.png\r\n11,https://cdn-icons-png.flaticon.com/256/8360/8360014.png,Access Denied,,e4248671046af773587308e3e12561c4.png\r\n12,https://cdn-icons-png.flaticon.com/256/8360/8360027.png,Access Denied,,4460c7884604344368cfecf43ef89f20.png\r\n13,https://cdn-icons-png.flaticon.com/512/8360/8360049.png,Monster,"smileys, halloween, spooky, scary, monster, terror, fear",a8b1af8dab6afcbf3412baca6347e1fb.png\r\n14,https://cdn-icons-png.flaticon.com/512/8360/8360051.png,Penguin,"animals, emotion, penguin, feeling, Puffin",60364b800f97f4133020bed7ad499ebb.png\r\n15,https://cdn-icons-png.flaticon.com/512/8360/8360097.png,Penguin,"animals, animal, love, message, penguin",016786983588d2b46d5bb3a96cea0b3d.png\r\n16,https://cdn-icons-png.flaticon.com/256/8360/8360119.png,Access Denied,,466f8a4c9e9cd7f1f42c1d9df9fadf85.png\r\n17,https://cdn-icons-png.flaticon.com/512/8360/8360131.png,Hedgehog,"smileys, emotions, happy, hedgehog",98fc43fb74931efc1cf69f0744b2bd84.png\r\n18,https://cdn-icons-png.flaticon.com/512/8360/8360137.png,Crocodile,"smileys, emotions, rest, crocodile, Alligator",dbcb5a66dd0bbe5dfe5f39dd22474dcf.png\r\n19,https://cdn-icons-png.flaticon.com/512/8360/8360148.png,Hedgehog,"smileys, emotions, hedgehog",87e364a07f792940b16b8fa3ec545ad3.png\r\n20,https://cdn-icons-png.flaticon.com/512/8362/8362077.png,Heart,"smileys, cultures, heart, traditional, mexican",4c9cee09802628c0fe094aaee8d54b86.png\r\n21,https://cdn-icons-png.flaticon.com/256/8362/8362083.png,Access Denied,,2e914abb3dc44c2ea6474915e18cb1f3.png\r\n22,https://cdn-icons-png.flaticon.com/512/8363/8363601.png,Bunny,"bunny, rabbit, healthcare and medical, medical, healthcare, doctor",d36debc81044ffbbdd89127fa910de4d.png\r\n23,https://cdn-icons-png.flaticon.com/256/8363/8363793.png,Access Denied,,4cb935a6b7e195f33cb9520b0e694fb2.png\r\n24,https://cdn-icons-png.flaticon.com/512/8363/8363809.png,Travel,"holidays, bunny, rabbit, travel, vacations, tourism, greece",45df56379728dad735c4de9e5b980449.png\r\n25,https://cdn-icons-png.flaticon.com/512/8366/8366015.png,Kdrama,"miscellaneous, lettering, typography, text, kpop, kdrama",a6ec4e3909348e7dc995cb911c85763e.png\r\n26,https://cdn-icons-png.flaticon.com/512/8366/8366091.png,Flamingo,"animals, smileys, wildlife, bird, zoology, flamingo",396acc967b3f20c7045100fb0931dd9a.png\r\n27,https://cdn-icons-png.flaticon.com/512/8366/8366129.png,Flamingo,"animals, smileys, wildlife, bird, zoology, flamingo",4ac02db1dc3f39a54cc2b8e617eb5927.png\r\n28,https://cdn-icons-png.flaticon.com/256/8376/8376276.png,Access Denied,,27a42747b4b683663fd2709935fed75d.png\r\n29,https://cdn-icons-png.flaticon.com/256/8392/8392249.png,Access Denied,,6cdab444b455da3a20e02bf757d3e775.png\r\n30,https://cdn-icons-png.flaticon.com/512/8401/8401818.png,Oktoberfest,"miscellaneous, lettering, typography, text, oktoberfest",cee94ec3a53a963e0df14cfeeed67e6f.png\r\n31,https://cdn-icons-png.flaticon.com/512/8401/8401828.png,Oktoberfest,"miscellaneous, lettering, typography, text, oktoberfest",a799fc3a021a5b976ecc9e9777a9b1a9.png\r\n32,https://cdn-icons-png.flaticon.com/512/8401/8401840.png,Oktoberfest,"miscellaneous, lettering, typography, text, oktoberfest",6ffc489bc27015a8e7159df2f564a391.png\r\n33,https://cdn-icons-png.flaticon.com/512/8401/8401851.png,Oktoberfest,"miscellaneous, lettering, typography, text, oktoberfest",1b9cf887e9527cccbed9a90f7a58ab76.png\r\n34,https://cdn-icons-png.flaticon.com/512/8401/8401860.png,Oktoberfest,"miscellaneous, lettering, typography, text, oktoberfest",9f32f2373c74cb9a7e6d48bf28342f48.png\r\n35,https://cdn-icons-png.flaticon.com/512/8401/8401871.png,Oktoberfest,"miscellaneous, lettering, typography, text, oktoberfest",d68f8fe65f28c0af906daddaa1698f82.png\r\n36,https://cdn-icons-png.flaticon.com/512/8401/8401881.png,Oktoberfest,"miscellaneous, lettering, typography, text, oktoberfest",60ea2a6540d704c9d5f381d337051bfe.png\r\n37,https://cdn-icons-png.flaticon.com/512/8401/8401892.png,Oktoberfest,"miscellaneous, lettering, typography, text, oktoberfest",4284c5079553794267480da14bac4e62.png\r\n38,https://cdn-icons-png.flaticon.com/512/8401/8401902.png,Oktoberfest,"miscellaneous, lettering, typography, text, oktoberfest",77444e2117421000b9b1b6fe892e5062.png\r\n39,https://cdn-icons-png.flaticon.com/512/8401/8401913.png,Oktoberfest,"miscellaneous, lettering, typography, text, oktoberfest",af0d85194a527f57c4878e62a73863c1.png\r\n40,https://cdn-icons-png.flaticon.com/512/8401/8401924.png,Oktoberfest,"miscellaneous, lettering, typography, text, oktoberfest",df720002af2e88518e431a9db86067b0.png\r\n41,https://cdn-icons-png.flaticon.com/512/8401/8401933.png,Oktoberfest,"miscellaneous, lettering, typography, text, oktoberfest",d1cbe2f21ad6ab528701164dd340869b.png\r\n42,https://cdn-icons-png.flaticon.com/512/8401/8401943.png,Oktoberfest,"miscellaneous, lettering, typography, text, oktoberfest",b693f48de7858ec24eea41c41957de1c.png\r\n43,https://cdn-icons-png.flaticon.com/512/8401/8401954.png,Oktoberfest,"miscellaneous, lettering, typography, text, oktoberfest",6711d13a72939399fb767c5c321bfaab.png\r\n44,https://cdn-icons-png.flaticon.com/512/8401/8401974.png,Oktoberfest,"miscellaneous, lettering, typography, text, oktoberfest",2774f130badff0c42add7462be26c523.png\r\n45,https://cdn-icons-png.flaticon.com/256/8401/8401985.png,Access Denied,,ec32d3259c75c29daa19ea03f0057935.png\r\n46,https://cdn-icons-png.flaticon.com/512/8401/8401996.png,Oktoberfest,"miscellaneous, lettering, typography, text, oktoberfest",217c0d1f30023ba0a4f185b5109e3b5c.png\r\n47,https://cdn-icons-png.flaticon.com/512/8402/8402007.png,Oktoberfest,"miscellaneous, lettering, typography, text, oktoberfest",2a4b34f89c3e0275865731a3b6f8f9b8.png\r\n48,https://cdn-icons-png.flaticon.com/512/8402/8402018.png,Oktoberfest,"miscellaneous, lettering, typography, text, oktoberfest",acf3e70b562906f3bc65044c2afae85b.png\r\n49,https://cdn-icons-png.flaticon.com/512/8408/8408188.png,Believe In You,"miscellaneous, lettering, typography, quote, phrase, encouraging",cbfe9f1120ff72f36f19ebc70b429075.png\r\n50,https://cdn-icons-png.flaticon.com/512/8408/8408191.png,Dont Give Up,"miscellaneous, lettering, typography, quote, phrase, encouraging, dont give up",3b5a088d670b1812511fb6d48bc2900a.png\r\n51,https://cdn-icons-png.flaticon.com/512/8408/8408199.png,Boy,"miscellaneous, lettering, typography, quote, phrase, boy, encouraging",c15e6d8fa80040eb0169b7831cb960f2.png\r\n52,https://cdn-icons-png.flaticon.com/256/8408/8408203.png,Access Denied,,3397c542e1922c9633defbb0188d9544.png\r\n53,https://cdn-icons-png.flaticon.com/512/8408/8408209.png,Girl,"miscellaneous, lettering, typography, quote, girl, phrase, encouraging",b9978511b6a7f14c1c03e0759610b633.png\r\n54,https://cdn-icons-png.flaticon.com/512/8408/8408216.png,Good Job,"miscellaneous, lettering, typography, quote, phrase, encouraging, good job",87cc80b847d3c8406f32f91c94459621.png\r\n55,https://cdn-icons-png.flaticon.com/512/8408/8408218.png,Dont Give Up,"miscellaneous, lettering, typography, quote, phrase, encouraging, dont give up",8410ae9e6bc8811792a3279f3dbb62ac.png\r\n56,https://cdn-icons-png.flaticon.com/256/8408/8408223.png,Access Denied,,dc9a9e0ccfa85cc975f50d6573aba2e8.png\r\n57,https://cdn-icons-png.flaticon.com/512/8408/8408231.png,Boy,"miscellaneous, lettering, typography, quote, phrase, boy, encouraging",529fa928d836f2d7dcfc816786198b8b.png\r\n58,https://cdn-icons-png.flaticon.com/512/8408/8408232.png,Proud,"miscellaneous, lettering, typography, quote, phrase, encouraging, proud",52a170e382b5897feda204797ba2508d.png\r\n59,https://cdn-icons-png.flaticon.com/512/8408/8408238.png,Effort,"miscellaneous, lettering, typography, quote, phrase, encouraging",2315abceaca8ca23028cc2e39ee9c57f.png\r\n60,https://cdn-icons-png.flaticon.com/512/8408/8408239.png,Encouraging,"miscellaneous, lettering, typography, quote, phrase, encouraging",5fe812ae42c18383aaeb4927c7345037.png\r\n61,https://cdn-icons-png.flaticon.com/512/8408/8408246.png,Fighting,"miscellaneous, lettering, typography, quote, phrase, encouraging, fighting",bdf5af25c3aff670ede21da141df715a.png\r\n62,https://cdn-icons-png.flaticon.com/512/8408/8408250.png,Good Job,"miscellaneous, lettering, typography, quote, phrase, encouraging, good job",664d227c0a529f1c5a701bd6f24f4187.png\r\n63,https://cdn-icons-png.flaticon.com/512/8408/8408253.png,Keep,"miscellaneous, lettering, typography, quote, phrase, encouraging",b263eca53e9ef077008f2439c894ad2d.png\r\n64,https://cdn-icons-png.flaticon.com/256/8408/8408259.png,Access Denied,,adcaa73d9dc38e9996a19719f78fe420.png\r\n65,https://cdn-icons-png.flaticon.com/512/8408/8408260.png,Trying,"miscellaneous, lettering, typography, quote, phrase, encouraging",4b5a46593591e824fc7acd7ad6ed5683.png\r\n66,https://cdn-icons-png.flaticon.com/512/8408/8408266.png,Proud,"miscellaneous, lettering, typography, quote, phrase, encouraging, proud",5cd0b1e3446aa861376e597e2b31a7fc.png\r\n67,https://cdn-icons-png.flaticon.com/512/8408/8408267.png,Pushing,"miscellaneous, lettering, typography, quote, phrase, encouraging",e6528fe0192c7bb0fe44b13563edc052.png\r\n68,https://cdn-icons-png.flaticon.com/512/8408/8408272.png,Encouraging,"miscellaneous, lettering, typography, quote, phrase, encouraging",133aedbb57f1ce479c0d162b139e267c.png\r\n69,https://cdn-icons-png.flaticon.com/512/8408/8408274.png,Encouraging,"miscellaneous, lettering, typography, quote, phrase, encouraging",e87886de76f23617327584b1b3887201.png\r\n70,https://cdn-icons-png.flaticon.com/512/8408/8408278.png,Fighting,"miscellaneous, lettering, typography, quote, phrase, encouraging, fighting",4ec5f1d22b8de0e19fd89343ae933fd9.png\r\n71,https://cdn-icons-png.flaticon.com/512/8408/8408281.png,Make It Happen,"miscellaneous, lettering, typography, quote, phrase, encouraging, make it happen",c715d657de7371295c1a82d18ba18d11.png\r\n72,https://cdn-icons-png.flaticon.com/512/8408/8408288.png,Never Give Up,"miscellaneous, lettering, typography, quote, phrase, encouraging, never give up",b3802bd56f904eb8d61e308ab3386794.png\r\n73,https://cdn-icons-png.flaticon.com/512/8408/8408295.png,Trying,"miscellaneous, lettering, typography, quote, phrase, encouraging",bd52169a3f9490709eddf71e727d1623.png\r\n74,https://cdn-icons-png.flaticon.com/512/8408/8408297.png,Going,"miscellaneous, lettering, typography, quote, phrase, encouraging",35f98bfab72f49e4d0b4bb31a479a984.png\r\n75,https://cdn-icons-png.flaticon.com/512/8408/8408303.png,Pushing,"miscellaneous, lettering, typography, quote, phrase, encouraging",0303c0042eccefcd03471692ab9bd066.png\r\n76,https://cdn-icons-png.flaticon.com/512/8408/8408305.png,Encouraging,"miscellaneous, lettering, typography, quote, phrase, encouraging",a8383301f87c49a36935b7dc8258b0e4.png\r\n77,https://cdn-icons-png.flaticon.com/512/8408/8408313.png,Encouraging,"miscellaneous, lettering, typography, quote, phrase, encouraging",5c3529c35196149c70f4e9b57ac80a23.png\r\n78,https://cdn-icons-png.flaticon.com/512/8408/8408319.png,Make It Happen,"miscellaneous, lettering, typography, quote, phrase, encouraging, make it happen",a5ff957661c4da191cc6474c06337c4f.png\r\n79,https://cdn-icons-png.flaticon.com/512/8408/8408321.png,Special,"miscellaneous, lettering, typography, quote, phrase, encouraging, special",65621fb324399d064a32fc0828accd5e.png\r\n80,https://cdn-icons-png.flaticon.com/512/8408/8408327.png,Never Give Up,"miscellaneous, lettering, typography, quote, phrase, encouraging, never give up",22027b7f4466234fb9a03f8e66b3bf53.png\r\n81,https://cdn-icons-png.flaticon.com/256/8408/8408334.png,Access Denied,,47ceefdf648f728cf074901ad4151bc2.png\r\n82,https://cdn-icons-png.flaticon.com/512/8408/8408342.png,Encouraging,"miscellaneous, lettering, typography, quote, phrase, encouraging",2fad949194f1c9b81103e6102a36d182.png\r\n83,https://cdn-icons-png.flaticon.com/256/8408/8408345.png,Access Denied,,f1a3f264516a8aa81dee8da1a256c0ac.png\r\n84,https://cdn-icons-png.flaticon.com/512/8408/8408346.png,You Can,"miscellaneous, lettering, typography, quote, phrase, encouraging",27d0bf9329eb805cd8abff9201bb4612.png\r\n85,https://cdn-icons-png.flaticon.com/512/8408/8408353.png,Encouraging,"miscellaneous, lettering, typography, quote, phrase, encouraging",55408ebf26394f5c4a815d07b97dd7a0.png\r\n86,https://cdn-icons-png.flaticon.com/512/8408/8408357.png,Special,"miscellaneous, lettering, typography, quote, phrase, encouraging, special",65baa509cd5df0dd4c7404ac895345c7.png\r\n87,https://cdn-icons-png.flaticon.com/512/8408/8408369.png,Capable,"miscellaneous, lettering, typography, quote, phrase, encouraging",bfb3b1111ae5a869e1a536daf839722a.png\r\n88,https://cdn-icons-png.flaticon.com/512/8408/8408375.png,Encouraging,"miscellaneous, lettering, typography, quote, phrase, encouraging",38d5a23263b04b46391ae1482c6c05aa.png\r\n89,https://cdn-icons-png.flaticon.com/512/8408/8408383.png,Encouraging,"miscellaneous, lettering, typography, quote, phrase, encouraging",4f75e5c62e8ac9b3367f81986d19ac37.png\r\n90,https://cdn-icons-png.flaticon.com/512/8408/8408602.png,Mental Health,"miscellaneous, lettering, typography, mental health, psychology",5baf270edd0aad7afc6e28b61b996585.png\r\n91,https://cdn-icons-png.flaticon.com/512/8408/8408622.png,Healthy Mind,"miscellaneous, lettering, typography, mental health, psychology",b759bbda37bf2ae800ec5753fca0af1e.png\r\n92,https://cdn-icons-png.flaticon.com/512/8408/8408675.png,Mental Health,"miscellaneous, lettering, typography, mental health, psychology",29fd78a15382914469eafd75a3b0b6b5.png\r\n93,https://cdn-icons-png.flaticon.com/512/8409/8409160.png,Line,"social media, social network",2584e05c729d62d467025050f6ed32de.png\r\n94,https://cdn-icons-png.flaticon.com/512/8421/8421255.png,Confused,"smileys, emoji, emoticon, astronomy, confused, full moon, astronomical",202f23a1d1196c52476544445abab775.png\r\n95,https://cdn-icons-png.flaticon.com/512/8421/8421272.png,Confused,"smileys, emoji, emoticon, confused, water drop",9ee368a16f4933d32fb3556c1b5ab7a9.png\r\n96,https://cdn-icons-png.flaticon.com/512/8421/8421303.png,Vain,"smileys, emoji, emoticon, astronomy, full moon, vain, astronomical",86afc47f7af73e1074095cfc1f0fe206.png\r\n97,https://cdn-icons-png.flaticon.com/512/8421/8421323.png,Sick,"smileys, emoji, emoticon, sick, water drop",d1f445b7554335bab5278fd519c59864.png\r\n98,https://cdn-icons-png.flaticon.com/512/8421/8421336.png,Tired,"smileys, emoji, emoticon, tired, water drop",5e043ec3fc8de9b52257538dce4f2a3b.png\r\n99,https://cdn-icons-png.flaticon.com/512/8431/8431847.png,And,"miscellaneous, lettering, typography, text, catchword, and",e9f5d0489689f4aadba96814ad65a4f9.png\r\n100,https://cdn-icons-png.flaticon.com/512/8431/8431849.png,Blah Blah Blah,"miscellaneous, lettering, typography, text, catchword",b09e513198d06e6cda9b9dcf02b2f097.png\r\n101,https://cdn-icons-png.flaticon.com/512/8431/8431854.png,By,"miscellaneous, lettering, typography, text, catchword, by",e77cec7bfd202e1aa776f140de19fa66.png\r\n102,https://cdn-icons-png.flaticon.com/512/8431/8431856.png,For,"miscellaneous, lettering, typography, text, catchword, for",9fa02736fcbb660ddc17c25d699db546.png\r\n103,https://cdn-icons-png.flaticon.com/512/8431/8431858.png,For,"miscellaneous, lettering, typography, text, catchword, for",1474b1278093bb2f5eab787cabd16432.png\r\n104,https://cdn-icons-png.flaticon.com/512/8431/8431860.png,Free,"miscellaneous, lettering, typography, text, catchword",e9b57250cce56798bb7790e0ead2f64d.png\r\n105,https://cdn-icons-png.flaticon.com/512/8431/8431862.png,Free,"miscellaneous, lettering, typography, text, catchword",7446ec69b1ab120b8daabe80cfa3df5b.png\r\n106,https://cdn-icons-png.flaticon.com/512/8431/8431864.png,And,"miscellaneous, lettering, typography, text, catchword, and",110c2f308956a27991c871091e88bba6.png\r\n107,https://cdn-icons-png.flaticon.com/512/8431/8431866.png,From,"miscellaneous, lettering, typography, text, catchword, from",16aeddc36a1f7775da262d5e7ea90531.png\r\n108,https://cdn-icons-png.flaticon.com/512/8431/8431869.png,Blah Blah Blah,"miscellaneous, lettering, typography, text, catchword",6697952544777df3b40f7b71aeeb5903.png\r\n109,https://cdn-icons-png.flaticon.com/512/8431/8431870.png,From,"miscellaneous, lettering, typography, text, catchword, from",6f63be851f925d16996e7589dc7ae90a.png\r\n110,https://cdn-icons-png.flaticon.com/256/8431/8431873.png,Access Denied,,810862e3dc8f062a716425282cc53011.png\r\n111,https://cdn-icons-png.flaticon.com/256/8431/8431874.png,Access Denied,,beb3698ac86b95500361ff598aaddc2a.png\r\n112,https://cdn-icons-png.flaticon.com/512/8431/8431877.png,By,"miscellaneous, lettering, typography, text, catchword, by",0d0f3eb98e2970a47b2d42973ef88461.png\r\n113,https://cdn-icons-png.flaticon.com/512/8431/8431878.png,Love You,"miscellaneous, lettering, typography, text, catchword, love you",189ba0cc3124e0184564ab7cf2f5f625.png\r\n114,https://cdn-icons-png.flaticon.com/256/8431/8431882.png,Access Denied,,02401319bd232a6a8ceae55727ad5589.png\r\n115,https://cdn-icons-png.flaticon.com/512/8431/8431886.png,Off,"miscellaneous, lettering, typography, text, catchword",dba020019b7f57b0cc6f3f57e13d4006.png\r\n116,https://cdn-icons-png.flaticon.com/256/8431/8431889.png,Access Denied,,d06766c741ded950565c0ebaf42a3ce4.png\r\n117,https://cdn-icons-png.flaticon.com/512/8431/8431890.png,On,"miscellaneous, lettering, typography, text, catchword",8fa0f3bca79926c83094f8f444cc4f69.png\r\n118,https://cdn-icons-png.flaticon.com/512/8431/8431894.png,Only,"miscellaneous, lettering, typography, text, catchword",c4f3c0dd486fe60964cf2603d42638bb.png\r\n119,https://cdn-icons-png.flaticon.com/512/8431/8431896.png,Free,"miscellaneous, lettering, typography, text, catchword",1bc96c25a21b5854795aff794c407a70.png\r\n120,https://cdn-icons-png.flaticon.com/512/8431/8431897.png,Free,"miscellaneous, lettering, typography, text, catchword",2844944b3d318a829f108fa850561502.png\r\n121,https://cdn-icons-png.flaticon.com/512/8431/8431898.png,Special,"miscellaneous, lettering, typography, text, catchword, special",fcf2cd3ff9b502bb6e124bb8204e5f1b.png\r\n122,https://cdn-icons-png.flaticon.com/512/8431/8431901.png,From,"miscellaneous, lettering, typography, text, catchword, from",d6d20c885ec1aa4fcfb46708d50a2763.png\r\n123,https://cdn-icons-png.flatico